config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :create, :show]
  resources :ingredients
  resources :users, only: [:index, :show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :ingredient
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_many :users, through: :allergies

  delegate :count, to: :users, prefix: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients, dependent: :destroy

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :recipe_ingredients, reject_if: :all_blank

  def ingredients=()
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  delegate :name, to: :ingredient
  delegate :title, to: :recipe
end

app/models/user.rb
class User < ApplicationRecord
  has_many :allergies, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all.sort_by(&:users_count).reverse
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


  before_action :get_recipe, only: [:update, :show,]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    3.times { @recipe.recipe_ingredients.build }
  end

  def create
    @recipe = Recipe.create!(recipe_params)
    redirect_to @recipe
  end

  def show
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :user_id, recipe_idingredients: [:quantity, :ingredient_id])
  end

  def get_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(params[:id])
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>Here are the Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Ingredient</th>
      <th>User Allergy Count</th>
    </tr>
  </thead>
  <tbody>
    <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= link_to "#{ingredient.name}", ingredient %></td>
      <td><%= ingredient.users_count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name.titleize %></h1>
<ul>
  <% @ingredient.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br/>
  <%= f.label :user_id %>
  <%= f.collection_select :user_id, User.all, :id, :name, prompt: true %><br>
  <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<table>

<thead>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th># of Ingredients</th>
  </tr>
</thead>

<tbody>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to recipe.title, recipe %></td>
      <td><%= link_to recipe.user.name, recipe.user %></td>
      <td><%= recipe.ingredients.count %></td>
    </tr>
  <% end %>
</tbody>



</table>

app/views/recipes/new.html.erb
<h1>Create a Recipe</h1>

<%= render "recipe_form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<ul>
  <% @recipe.recipe_ingredients.each do |ri| %>
    <li><%= link_to pluralize(ri.quantity, ri.name), ri.ingredient %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name.titleize %></h1>

<h2>Recipes<h2>
<ul>
  <% @user.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe %></li>
  <% end %>
</ul>

<%= button_to "Delete", @user, method: :delete, data: { confirm: "Really?" } %>